#!/usr/bin/env node
/* ============================================================
   TEST CHAIN CURTAINS & KEYS (v1.8.0)
   Esegue: node games/mahjong/tests/test-chains.js

   Controlli:
     1. Esattamente 32 livelli hanno isChain === true nella progressione di 330 livelli (da L13 in poi, finale 3).
     2. Tutti i livelli catena generano un oggetto tiles.chain valido con stages.
     3. Tutte le chiavi generate non sono mai coperte (faceDown) né oscurate (obscured).
     4. Le tessere incatenate non sono mai libere (isFree === false) finché il rispettivo stadio è chiuso.
     5. Quando le chiavi di uno stadio vengono rimosse, lo stadio risulta sbloccabile (isChainStageUnlocked).
     6. Sbloccando lo stadio, le tessere incatenate perdono lo stato di blocco catena.
     7. Giocabilità all'avvio: ogni livello catena ha almeno una coppia libera matchabile.
   ============================================================ */
const fs = require('fs');
const vm = require('vm');
const path = require('path');

const dir = path.join(__dirname, '..');
const ctx = { console, process, setTimeout, clearTimeout };
vm.createContext(ctx);

const load = [
  fs.readFileSync(path.join(dir, 'layouts.js'), 'utf8'),
  fs.readFileSync(path.join(dir, 'solvable-levels.js'), 'utf8'),
  fs.readFileSync(path.join(dir, 'engine.js'), 'utf8'),
  fs.readFileSync(path.join(dir, 'data.js'), 'utf8')
].join('\n') + '\n' + [
  '(function () {',
  '  let failures = 0;',
  '',
  '  const progression = ensureProgression();',
  '  const chainLevels = [];',
  '  for (let i = 0; i < progression.length; i++) {',
  '    if (progression[i].isChain) chainLevels.push(i);',
  '  }',
  '',
  '  console.log("Totale livelli catena trovati: " + chainLevels.length + " (attesi 32)");',
  '  if (chainLevels.length !== 32) {',
  '    failures++;',
  '    console.log("FAIL: attesi 32 livelli catena, trovati " + chainLevels.length);',
  '  }',
  '',
  '  chainLevels.forEach(function (idx) {',
  '    const def = getLevelDef(idx);',
  '    const lvlNum = idx + 1;',
  '    if (!def.isChain) {',
  '      failures++;',
  '      console.log("FAIL: L" + lvlNum + " getLevelDef.isChain non e true");',
  '    }',
  '',
  '    const tiles = generateLevel(idx);',
  '    const chain = tiles.chain;',
  '    if (!chain) {',
  '      failures++;',
  '      console.log("FAIL: L" + lvlNum + " tiles.chain e mancante");',
  '      return;',
  '    }',
  '',
  '    if (!chain.stages || !chain.stages.length) {',
  '      failures++;',
  '      console.log("FAIL: L" + lvlNum + " chain.stages e vuoto");',
  '      return;',
  '    }',
  '',
  '    const board = buildBoard(tiles);',
  '    board._chain = chain;',
  '',
  '    /* Verifica che nessuna chiave sia faceDown o obscured */',
  '    let totalKeyTiles = 0;',
  '    tiles.forEach(function (t) {',
  '      if (t.isKey) {',
  '        totalKeyTiles++;',
  '        if (t.faceDown) {',
  '          failures++;',
  '          console.log("FAIL: L" + lvlNum + " key tile e faceDown!");',
  '        }',
  '        if (t.obscured) {',
  '          failures++;',
  '          console.log("FAIL: L" + lvlNum + " key tile e obscured!");',
  '        }',
  '      }',
  '    });',
  '',
  '    const expectedKeys = chain.stages.length * 2;',
  '    if (totalKeyTiles !== expectedKeys) {',
  '      failures++;',
  '      console.log("FAIL: L" + lvlNum + " attese " + expectedKeys + " tessere chiave, trovate " + totalKeyTiles);',
  '    }',
  '',
  '    /* Verifica che ogni stadio abbia chiavi e tessere incatenate */',
  '    chain.stages.forEach(function (st, sIdx) {',
  '      if (!st.keyTileKeys || st.keyTileKeys.length !== 2) {',
  '        failures++;',
  '        console.log("FAIL: L" + lvlNum + " stage " + (sIdx+1) + " keyTileKeys non ha 2 chiavi: " + JSON.stringify(st.keyTileKeys));',
  '      }',
  '      if (!st.chainedKeys || st.chainedKeys.length === 0) {',
  '        failures++;',
  '        console.log("FAIL: L" + lvlNum + " stage " + (sIdx+1) + " chainedKeys e vuoto");',
  '      }',
  '      if (isChainStageUnlocked(sIdx, chain, board)) {',
  '        failures++;',
  '        console.log("FAIL: L" + lvlNum + " stage " + (sIdx+1) + " risulta sbloccato all avvio");',
  '      }',
  '    });',
  '',
  '    /* Verifica che le tessere incatenate non siano isFree all avvio */',
  '    tiles.forEach(function (t) {',
  '      if (isTileChained(t, chain)) {',
  '        if (isFree(board, t)) {',
  '          failures++;',
  '          console.log("FAIL: L" + lvlNum + " tile incatenato " + t.key + " risulta isFree!");',
  '        }',
  '      }',
  '    });',
  '',
  '    /* Verifica simulazione sblocco: rimuovendo le chiavi di stage 0, lo stage si sblocca */',
  '    const stage0 = chain.stages[0];',
  '    stage0.keyTileKeys.forEach(function (k) {',
  '      const kt = board.get(k);',
  '      if (kt) kt.removed = true;',
  '    });',
  '    if (!isChainStageUnlocked(0, chain, board)) {',
  '      failures++;',
  '      console.log("FAIL: L" + lvlNum + " stage 0 non si sblocca dopo aver rimosso le chiavi");',
  '    }',
  '',
  '    // Reset per controllo giocabilita',
  '    stage0.keyTileKeys.forEach(function (k) {',
  '      const kt = board.get(k);',
  '      if (kt) kt.removed = false;',
  '    });',
  '',
  '    /* Verifica giocabilita all avvio: almeno 1 coppia libera matchabile o >= 4 free */',
  '    const freeList = [];',
  '    tiles.forEach(function (t) {',
  '      if (!t.removed && !t.staging && !t.faceDown && !t.obscured && isFree(board, t)) {',
  '        freeList.push(t);',
  '      }',
  '    });',
  '',
  '    let hasPair = false;',
  '    for (let f1 = 0; f1 < freeList.length; f1++) {',
  '      for (let f2 = f1 + 1; f2 < freeList.length; f2++) {',
  '        if (canMatch(freeList[f1], freeList[f2], def.mode)) { hasPair = true; break; }',
  '      }',
  '      if (hasPair) break;',
  '    }',
  '    if (!hasPair && freeList.length < 4) {',
  '      failures++;',
  '      console.log("FAIL: L" + lvlNum + " non ha coppie libere matchabili all avvio (free: " + freeList.length + ")");',
  '    }',
  '  });',
  '',
  '  if (failures === 0) {',
  '    console.log("PASS — Tutti i 32 livelli catena verificati con successo!");',
  '    process.exit(0);',
  '  } else {',
  '    console.log("FAIL — Rilevati " + failures + " errori nei livelli catena.");',
  '    process.exit(1);',
  '  }',
  '})();'
].join('\n');

vm.runInContext(load, ctx);
